package GUI;

import civitas.CivitasJuego;
import civitas.Jugador;
import civitas.OperacionesJuego;
import civitas.SalidasCarcel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

public class CivitasView extends javax.swing.JFrame {

    private CivitasJuego juego;
    private JugadorPanel jugadorPanel;
    private CasillaPanel casillaPanel;
    
    public void setCivitasJuego(CivitasJuego _civitas){
        juego=_civitas;
        this.setVisible(true);
    }
    
    public void actualizarVista(){
        jugadorPanel.setJugador(juego.getJugadorActual());
        casillaActual.setText(juego.getCasillaActual().toString());
        jugadorPanel.setVisible(true);
        casillaActual.setVisible(true);
        
        Ranking.setVisible(false);
        this.TextRanking.setVisible(false);
        if(juego.finalDelJuego()){
            ArrayList<Jugador> rank = juego.ranking();
            String r = "";
            for(int i = 0; i<rank.size();i++){
                r=r+rank.get(i).toString() + "\n";
            }
            Ranking.setText(r);
            Ranking.setVisible(true);
            this.TextRanking.setVisible(true);
        }
        this.repaint();
        this.revalidate();
    }
    
    void mostrarSiguienteOperacion(OperacionesJuego _operacion){
        SiguienteOperacion.setText(_operacion.toString());
        SiguienteOperacion.setVisible(true);
        this.actualizarVista();
    }
    
    GestionarDialog gestionarD = new GestionarDialog(this);
    
    int getGestion(){
        return gestionarD.getGestionElegida();
    }
    
    int getPropiedad(){
        return gestionarD.getPropiedadElegida();
    }
    
    public void gestionar(){
        gestionarD.gestionar(juego.getJugadorActual());
        gestionarD.pack();
        gestionarD.repaint();
        gestionarD.revalidate();
        gestionarD.setVisible(true);
    }
    
    Respuestas comprar(){
        int res = JOptionPane.showConfirmDialog(null, "¿Desea comprar la siguiente calle?", "Comprar", JOptionPane.YES_NO_OPTION);
        return(Respuestas.values()[res]);
    }
    
    void mostrarEventos(){
        DiarioDialog diarioD = new DiarioDialog(this);
    }
    
    SalidasCarcel salirCarcel(){
        String[] opciones={"PAGANDO", "TIRANDO"};
        int res = JOptionPane.showOptionDialog(null, "¿Como ha de salir de la carcel?", "SALIR de la CARCEL", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
        return (SalidasCarcel.values()[res]);
    }
    
    public CivitasView() {
        initComponents();
        jugadorPanel = new JugadorPanel();
        contenedorVistaJugador.add(jugadorPanel);
        casillaPanel = new CasillaPanel();
        casillaActual.add(casillaPanel);
        this.repaint();
        this.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CivitasView = new javax.swing.JLabel();
        contenedorVistaJugador = new javax.swing.JPanel();
        casillaActual = new javax.swing.JTextField();
        SiguienteOperacion = new javax.swing.JLabel();
        siguienteOperacion = new javax.swing.JTextField();
        Ranking = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextRanking = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CivitasView.setText("CivitasView");
        CivitasView.setEnabled(false);

        casillaActual.setText("Casilla");
        casillaActual.setEnabled(false);

        SiguienteOperacion.setText("SiguienteOp");
        SiguienteOperacion.setEnabled(false);

        siguienteOperacion.setText("SiguienteOperacion");
        siguienteOperacion.setEnabled(false);
        siguienteOperacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteOperacionActionPerformed(evt);
            }
        });

        Ranking.setText("Ranking");
        Ranking.setEnabled(false);

        TextRanking.setColumns(20);
        TextRanking.setRows(5);
        TextRanking.setEnabled(false);
        jScrollPane1.setViewportView(TextRanking);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CivitasView))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(siguienteOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(casillaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(92, 92, 92)
                                .addComponent(SiguienteOperacion))
                            .addComponent(Ranking))))
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CivitasView)
                .addGap(27, 27, 27)
                .addComponent(contenedorVistaJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(casillaActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiguienteOperacion)
                    .addComponent(siguienteOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addComponent(Ranking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siguienteOperacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteOperacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siguienteOperacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CivitasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CivitasView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CivitasView;
    private javax.swing.JLabel Ranking;
    private javax.swing.JLabel SiguienteOperacion;
    private javax.swing.JTextArea TextRanking;
    private javax.swing.JTextField casillaActual;
    private javax.swing.JPanel contenedorVistaJugador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField siguienteOperacion;
    // End of variables declaration//GEN-END:variables
}
