package GUI;

import civitas.Jugador;
import civitas.TituloPropiedad;
import java.util.ArrayList;

public class JugadorPanel extends javax.swing.JPanel {

    Jugador jugador;
    public void setJugador(Jugador _jugador){
        nombre.setText(_jugador.getNombre());
        saldo.setText(Float.toString(_jugador.getSaldo()));
        encarcelado.setText(Boolean.toString(_jugador.isEncarcelado()));
        especulador.setText(Boolean.toString(_jugador.soyEspeculador()));
        numCasillaActual.setText(Integer.toString(_jugador.getNumCasillaActual()));
        this.rellenarPropiedades(_jugador.getPropiedades());
        this.repaint();
        
    }
    
    
    public void rellenarPropiedades(ArrayList<TituloPropiedad> lista){
        //Se elimina la informacion antigua
        propiedades.removeAll();
        //Se recorre la lista de propiedades para ir creando sus vistas individuales y añadirlas al panel
        for(TituloPropiedad t:lista){
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);
            propiedades.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
        //Se fuerza la actualización visual del panel de propiedades y del panel del jugador
        this.repaint();
        this.revalidate();
    }
    
    public JugadorPanel() {
        initComponents();
    }

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        saldo = new javax.swing.JLabel();
        Saldo = new javax.swing.JTextField();
        encarcelado = new javax.swing.JLabel();
        Encarcelado = new javax.swing.JTextField();
        especulador = new javax.swing.JLabel();
        Especulador = new javax.swing.JTextField();
        PanelPropiedades = new javax.swing.JPanel();
        propiedades = new javax.swing.JPanel();
        numCasillaActual = new javax.swing.JLabel();
        numCasillaTexto = new javax.swing.JTextField();

        setEnabled(false);

        nombre.setText("Nombre");
        nombre.setEnabled(false);

        Nombre.setText("Nombre");
        Nombre.setEnabled(false);
        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });

        saldo.setText("Saldo");
        saldo.setEnabled(false);

        Saldo.setText("Saldo:");
        Saldo.setEnabled(false);
        Saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaldoActionPerformed(evt);
            }
        });

        encarcelado.setText("Encarcelado");
        encarcelado.setEnabled(false);

        Encarcelado.setText("Estoy encarcelado");
        Encarcelado.setEnabled(false);
        Encarcelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EncarceladoActionPerformed(evt);
            }
        });

        especulador.setText("Especulador");
        especulador.setEnabled(false);

        Especulador.setText("Soy especulador");
        Especulador.setEnabled(false);
        Especulador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EspeculadorActionPerformed(evt);
            }
        });

        numCasillaActual.setText("NumCasillaActual");
        numCasillaActual.setEnabled(false);

        numCasillaTexto.setText("Numero Casilla Actual");
        numCasillaTexto.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saldo)
                                    .addComponent(nombre)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Encarcelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Especulador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numCasillaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(especulador)
                                    .addComponent(encarcelado)
                                    .addComponent(propiedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numCasillaActual)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(PanelPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saldo)
                    .addComponent(Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encarcelado)
                    .addComponent(Encarcelado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(especulador)
                    .addComponent(Especulador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numCasillaActual)
                    .addComponent(numCasillaTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(propiedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(PanelPropiedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void SaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaldoActionPerformed

    private void EncarceladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EncarceladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EncarceladoActionPerformed

    private void EspeculadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EspeculadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EspeculadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Encarcelado;
    private javax.swing.JTextField Especulador;
    private javax.swing.JTextField Nombre;
    private javax.swing.JPanel PanelPropiedades;
    private javax.swing.JTextField Saldo;
    private javax.swing.JLabel encarcelado;
    private javax.swing.JLabel especulador;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel numCasillaActual;
    private javax.swing.JTextField numCasillaTexto;
    private javax.swing.JPanel propiedades;
    private javax.swing.JLabel saldo;
    // End of variables declaration//GEN-END:variables
}
