/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import civitas.TituloPropiedad;

/**
 *
 * @author juancarlosgq
 */
public class PropiedadPanel extends javax.swing.JPanel {

    
    TituloPropiedad titulo;
    
    public void setPropiedad(TituloPropiedad _titulo){
        nombrePropiedad.setText(_titulo.getNombre());
        numCasas.setText(Integer.toString(_titulo.getNumCasas()));
        numHoteles.setText(Integer.toString(_titulo.getNumHoteles()));
        hipotecada.setText(Boolean.toString(_titulo.getHipotecado()));
        //this.repaint();
    }
    
    public PropiedadPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombrePropiedad = new javax.swing.JLabel();
        numCasas = new javax.swing.JLabel();
        numHoteles = new javax.swing.JLabel();
        hipotecada = new javax.swing.JLabel();
        NombrePropiedad = new javax.swing.JTextField();
        NumCasas = new javax.swing.JTextField();
        NumHoteles = new javax.swing.JTextField();
        Hipotecada = new javax.swing.JTextField();

        nombrePropiedad.setText("nombrePropiedad");
        nombrePropiedad.setEnabled(false);

        numCasas.setText("numCasas");
        numCasas.setEnabled(false);

        numHoteles.setText("numHoteles");
        numHoteles.setEnabled(false);

        hipotecada.setText("hipotecada");
        hipotecada.setEnabled(false);

        NombrePropiedad.setText("Nombre de la propiedad");
        NombrePropiedad.setEnabled(false);
        NombrePropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombrePropiedadActionPerformed(evt);
            }
        });

        NumCasas.setText("Numero de Casas");
        NumCasas.setEnabled(false);

        NumHoteles.setText("Numero de Hoteles");
        NumHoteles.setEnabled(false);

        Hipotecada.setText("Estoy hipotecada");
        Hipotecada.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NombrePropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NumHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Hipotecada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hipotecada)
                    .addComponent(numHoteles)
                    .addComponent(numCasas)
                    .addComponent(nombrePropiedad))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombrePropiedad)
                    .addComponent(NombrePropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numCasas)
                    .addComponent(NumCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numHoteles)
                    .addComponent(NumHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hipotecada)
                    .addComponent(Hipotecada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(145, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void NombrePropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombrePropiedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombrePropiedadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Hipotecada;
    private javax.swing.JTextField NombrePropiedad;
    private javax.swing.JTextField NumCasas;
    private javax.swing.JTextField NumHoteles;
    private javax.swing.JLabel hipotecada;
    private javax.swing.JLabel nombrePropiedad;
    private javax.swing.JLabel numCasas;
    private javax.swing.JLabel numHoteles;
    // End of variables declaration//GEN-END:variables
}
